# www.avery.workers.dev
name = "www"
type = "webpack"
workers_dev = true

# for `wrangler dev --env dev` only
[env.dev]
name = "dev"
vars = { DEBUG_FLAG = "on" }

# staging.averyharnish.com
[env.staging]
route = "staging.averyharnish.com/*"

# averyharnish.com
[env.production]
route = "averyharnish.com/*"

[site]
bucket = "./public"
entry-point = "workers-site"
