# www.avery.workers.dev
name = "www"
type = "webpack"
workers_dev = true

[env.clarktime-dev]
name = "clarktime"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

# averyharnish.com
[env.production]
route = "averyharnish.com/*"