on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vercel preview URL
        run: echo ::set-env name=VERCEL_URL::avery-site-git-${${GITHUB_REF/refs\/heads\//}//\//-}-averyharnish.vercel.app
      - name: Print VERCEL_URL
        run: echo ${VERCEL_URL}
      - name: Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v8.0.1
        with:
          urls: '${VERCEL_URL}'
          prCommentEnabled: true