on: [push]
jobs:
  lighthouse:
    if: startsWith(github.head_ref, 'lighthouse-patches') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set lighthouse patch branch name
        id: patch-branch
        run: echo ::set-output name=branch-name::"lighthouse-patches/${{ github.head_ref }}"
      - name: Get Vercel preview URL
        run: BRANCH=${GITHUB_REF/refs\/heads\//}; echo ::set-output name=url::https://avery-site-git-${BRANCH/\//-}-averyharnish.vercel.app
        id: vercel
      - name: Run Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v8.0.1
        id: lighthouse-raw
        with:
          urls: ${{ steps.vercel.outputs.url }}
      - name: Transform lighthouse output
        id: lighthouse
        run: SCORES=$(echo '${{ steps.lighthouse-raw.outputs.lighthouseCheckResults }}' | jq '.data[0].scores'); echo ::set-output name=accessibility:$(echo $SCORES | jq .accessibility); echo ::set-output name=bestPractices:$(echo $SCORES | jq .bestPractices); echo ::set-output name=performance:$(echo $SCORES | jq .performance); echo ::set-output name=seo:$(echo $SCORES | jq .seo)
      - name: Update scores.json
        id: update-scores
        run: node -e 'require("./lighthouse/src/scores.js").update(${{ steps.lighthouse.outputs.accessibility }}, ${{ steps.lighthouse.outputs.bestPractices }}, ${{ steps.lighthouse.outputs.performance }}, ${{ steps.lighthouse.outputs.seo }})'
      - name: Update badges
        if: ${{ steps.update-scores.outputs.changed }} == "true"
        run: npm run badges
      - name: Create PR with Lighthouse results
        if: ${{ steps.update-scores.outputs.changed }} == "true"
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: updates lighthouse badges'
          title: "chore: updates lighthouse badges for '${{ github.head_ref }}' branch"
          branch: ${{ steps.patch-branch.outputs.branch-name }}
