on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vercel preview URL
        shell: bash
        run: BRANCH=${GITHUB_REF/refs\/heads\//}; echo ::set-output name=VERCEL_URL::avery-site-git-${BRANCH/\//-}-averyharnish.vercel.app
        id: vercel
      - name: Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v8.0.1
        with:
          urls: ${{ steps.vercel.outputs.VERCEL_URL }}
          prCommentEnabled: true