on: [push]

jobs:
  lighthouse:
    if: startsWith(github.head_ref, 'lighthouse-patches') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Get branch name
        id: git-branch
        run: echo ::set-output name=name::${GITHUB_REF/refs\/heads\//}

      - name: Set lighthouse patch branch name
        id: patch-branch
        run: echo ::set-output name=name::"lighthouse-patches/${{ steps.git-branch.outputs.name }}"

      - name: Normalize branch for Vercel
        id: normalize-branch
        run: BRANCH=${{ steps.git-branch.outputs.name }}; echo ::set-output name=name::${BRANCH/\//-}

      - name: Get Vercel preview URL
        run: echo ::set-output name=url::https://avery-site-git-${{ steps.normalize-branch.outputs.name }}-averyharnish.vercel.app
        id: vercel

      - name: Run Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v8.0.1
        id: lighthouse
        with:
          urls: ${{ steps.vercel.outputs.url }}

      - name: Save Lighthouse output to file
        run: echo '${{ steps.lighthouse.outputs.lighthouseCheckResults }}' > ./lighthouse/report.json

      - name: Generate Lighthouse badges
        id: badges
        run: npm i; npm run badges

      - name: Create PR with Lighthouse results
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: updates lighthouse badges"
          title: "chore: updates lighthouse badges for `${{ steps.git-branch.outputs.name }}`"
          branch: ${{ steps.patch-branch.outputs.name }}
