on: [push]
jobs:
  lighthouse:
    if: startsWith(github.head_ref, 'lighthouse-patches') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set lighthouse patch branch name
        id: patch-branch
        run: echo ::set-output name=branch-name::"lighthouse-patches/${{ github.head_ref }}"
      - name: Get Vercel preview URL
        run: BRANCH=${GITHUB_REF/refs\/heads\//}; echo ::set-output name=url::https://avery-site-git-${BRANCH/\//-}-averyharnish.vercel.app
        id: vercel
      - name: Run Lighthouse Audit
        uses: foo-software/lighthouse-check-action@v8.0.1
        id: lighthouse
        with:
          urls: ${{ steps.vercel.outputs.url }}
      - name: Update scores.json
        id: scores
        run: echo ${{ steps.lighthouse.outputs.lighthouseCheckResults }}; node -e 'require("./lighthouse/src/scores.js").update(${{ steps.lighthouse.outputs.lighthouseCheckResults.scores.accessibility }}, ${{ steps.lighthouse.outputs.lighthouseCheckResults.scores.bestPractices }}, ${{ steps.lighthouse.outputs.lighthouseCheckResults.scores.performance }}, ${{ steps.lighthouse.outputs.lighthouseCheckResults.scores.seo }})'
      - name: Update badges
        if: ${{ steps.scores.outputs.changed }} == "true"
        run: npm run badges
      - name: Create PR with Lighthouse results
        if: ${{ steps.scores.outputs.changed }} == "true"
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: updates lighthouse badges'
          title: "chore: updates lighthouse badges for '${{ github.head_ref }}' branch"
          branch: ${{ steps.patch-branch.outputs.branch-name }}
